repository = "novanet"
network = "10.123.123.0/24"
domain = "blackmesa.labs"

[peers.uovobw-giove]
username = "uovobw"
peername = "giove"
address = "10.123.123.128/24"
listen_port = 6666
public_key = "kPECk78/vC7hRKWXtL4KYG99J41C22XvzEmP0yl3RQU="
allowed_ips = ["10.123.123.128/32"]
persistent_keepalive = 25
endpoint = "giove.uovobw.net"
mtu = 1500

[peers.uovobw-saturno]
username = "uovobw"
peername = "saturno"
address = "10.123.123.155/24"
listen_port = 6666
public_key = "7Xnm5MoqKVdjJrktqsZxgTY7+1MXHk8wBHIoFnpTWyk="
allowed_ips = ["10.123.123.155/32"]
persistent_keepalive = 25
endpoint = "saturno.uovobw.net"
mtu = 1500

[peers.uovobw-marte]
username = "uovobw"
peername = "marte"
address = "10.123.123.80/24"
listen_port = 6666
public_key = "cHo4d+FyLjbefzOPjgDfXn2v40TUn7nLt6vnZiT5Kw8="
allowed_ips = ["10.123.123.80/32"]
persistent_keepalive = 25
endpoint = "marte.uovobw.net"
mtu = 1500
