repository = "novanet"
network = "10.123.123.0/24"
domain = "blackmesa.labs"
[peers.bigo-home-uk]
username = "bigo"
peername = "home-uk"
address = "10.123.123.60/24"
listen_port = 6666
public_key = "T/HmYDWDJzcGO1DQRWBmsC2YvfSaSCz4zCv495Z64T8="
allowed_ips = ["10.123.123.60/32"]
persistent_keepalive = 0
endpoint = "crisidev.org"
mtu = 1500
